<a href="https://colab.research.google.com/github/arooba-zaman1211/Deep_Learning_using_Pytorch/blob/main/Lesson_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import the torch library
import torch

In [2]:
# make a tensor of rand size 3 rows and 4 columns and dimension 2
new_tensor = torch.rand(3,4)
new_tensor

tensor([[0.0180, 0.0242, 0.4184, 0.4218],
        [0.0874, 0.9640, 0.2846, 0.2083],
        [0.3994, 0.3203, 0.0224, 0.0095]])

In [17]:
# extract the 1st row of the tensor
second_tensor = new_tensor[1,:]
second_tensor

tensor([0., 0., 0., 0.])

In [18]:
# make a zeros tensor same dimension as of second tensor
zeros = torch.zeros_like(second_tensor)

In [19]:
# multiply the zeros and the second_tensor
updated = zeros * second_tensor

In [20]:
updated

tensor([0., 0., 0., 0.])

In [21]:
# update the new_tensor after the multiplication with the new calculated values
new_tensor[1,:] = updated
new_tensor

tensor([[0.0180, 0.0242, 0.4184, 0.4218],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.3994, 0.3203, 0.0224, 0.0095]])

In [22]:
# the default type of values in tensor is float
new_tensor.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [26]:
range = torch.arange(0, 10)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
likeTensor = torch.ones_like(range)
likeTensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
range = torch.arange(start=1 , end=11 , step=2)
range

tensor([1, 3, 5, 7, 9])

### Data types in tensors

#### Tensors datatypes is one of the three big errors we run into
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [33]:
float32_tensor = torch.tensor([1.2, 2.4, 3.0],
                              dtype = torch.float32, # the data type of tensor
                              device= None, # We need to define device like cpu and gpu so that we don't get device we running on errors by default:cpu
                              requires_grad= False)
float32_tensor.dtype

torch.float32

In [34]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor.dtype

torch.float16