<a href="https://colab.research.google.com/github/arooba-zaman1211/Deep_Learning_using_Pytorch/blob/main/Lesson_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch tensors and Numpy

* Data in numpy to pytorch tensor -> `torch.from_numpy(ndarray)`
* Data from tensor to numpy array -> `torch.tensor.numpy()`

In [1]:
import torch
import numpy as np

In [4]:
array = np.arange(1.0 , 9.0)
tensor = torch.from_numpy(array) # pytorch reflects the default data type of numpy that is float64 in this case
tensor , array

(tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7., 8.]))

In [5]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [8]:
array = tensor.numpy()
array

array([1., 2., 3., 4., 5., 6., 7., 8.])

### Pytorch reproducibility

To reduce the randomess of values the concept of `random seed` comes into picture

In [9]:
tensor_1 = torch.rand(3,4)
tensor_2 = torch.rand(3,4)

print(tensor_1)
print(tensor_2)
print(tensor_1 == tensor_2)

tensor([[0.2062, 0.1756, 0.0899, 0.7550],
        [0.1280, 0.0608, 0.5197, 0.0743],
        [0.5894, 0.8569, 0.5711, 0.1407]])
tensor([[0.0062, 0.4143, 0.2576, 0.0654],
        [0.4701, 0.3141, 0.8269, 0.7657],
        [0.8490, 0.2362, 0.4522, 0.8665]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [12]:
# here we have controlled the randomness by using manual random seed value
Random_seed = 22
torch.manual_seed(Random_seed)
tensor_1 = torch.rand(3,4)

torch.manual_seed(Random_seed)
tensor_2 = torch.rand(3,4)

print(tensor_1)
print(tensor_2)
print(tensor_1 == tensor_2)

tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[0.3659, 0.7025, 0.3104, 0.0097],
        [0.6577, 0.1947, 0.9506, 0.6887],
        [0.8174, 0.7575, 0.7492, 0.6874]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [13]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'