<a href="https://colab.research.google.com/github/arooba-zaman1211/Deep_Learning_using_Pytorch/blob/main/Lesson_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
int_32_tensor = torch.tensor([1.3,2.5,7.6],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 7], dtype=torch.int32)

In [4]:
int_32_tensor.dtype

torch.int32

### Getting information from tensors (tensor attributes)

1. datatype - tensor.dtype
2. shape - tensor.shape
3. device - tensor.device

In [5]:
tensor = torch.rand(3,4)
tensor

tensor([[0.7904, 0.4610, 0.1007, 0.1575],
        [0.3543, 0.5273, 0.8053, 0.8723],
        [0.1608, 0.5446, 0.1344, 0.8778]])

In [6]:
tensor.dtype

torch.float32

In [7]:
tensor.shape

torch.Size([3, 4])

In [8]:
tensor.device

device(type='cpu')

In [15]:
tensor_2 = torch.randint(low=0, high=10,size = (2,4), dtype=torch.int16, device = 'cpu')
tensor_2

tensor([[9, 3, 5, 5],
        [5, 7, 6, 2]], dtype=torch.int16)

In [16]:
print(f"tensor_2 datatype: {tensor_2.dtype}")
print(f"tensor_2 device: {tensor_2.device}")
print(f"tensor_2 shape: {tensor_2.shape}")

tensor_2 datatype: torch.int16
tensor_2 device: cpu
tensor_2 shape: torch.Size([2, 4])


### Manipulating Tensor (tensor operations)

1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [17]:
tensor_2 + 10

tensor([[19, 13, 15, 15],
        [15, 17, 16, 12]], dtype=torch.int16)

In [18]:
tensor_2 - 10

tensor([[-1, -7, -5, -5],
        [-5, -3, -4, -8]], dtype=torch.int16)

In [19]:
tensor_2 / 10

tensor([[0.9000, 0.3000, 0.5000, 0.5000],
        [0.5000, 0.7000, 0.6000, 0.2000]])

In [20]:
tensor_2 * 10

tensor([[90, 30, 50, 50],
        [50, 70, 60, 20]], dtype=torch.int16)

In [21]:
# pytorch pre-defined functions
torch.mul(tensor_2, 10)

tensor([[90, 30, 50, 50],
        [50, 70, 60, 20]], dtype=torch.int16)

In [22]:
torch.add(tensor_2, 10)

tensor([[19, 13, 15, 15],
        [15, 17, 16, 12]], dtype=torch.int16)

### Matrix Multiplication

Two main ways of multiplication in neural networks and deep learning are:
1. Element wise multiplication
2. Matrix multiplication (dot product)