<a href="https://colab.research.google.com/github/arooba-zaman1211/Deep_Learning_using_Pytorch/blob/main/Lesson_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

### Tensor Aggregations (min, max, mean, sum etc)

These are called tensor aggregations cause result in a single value from a tensor.<br>
Mean can not be calculated of tensor of dtype other than float

In [2]:
# range of numbers created
x = torch.arange(0, 100, 10)
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [3]:
# minimum of tensor
x.min()

tensor(0)

In [4]:
# max of tensor
x.max()

tensor(90)

In [7]:
# changing the type from int to float
tensor = torch.tensor(x, dtype=torch.float32)
tensor.dtype

<ipython-input-7-bf88234dc51c>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(x, dtype=torch.float32)


torch.float32

In [10]:
# the mean is not found until the dtype of tensor is float
tensor.mean() , tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [14]:
tensor.sum()

tensor(450.)

### Get the index of min and max values in a tensor

In [16]:
tensor.argmin() , tensor.argmax()

(tensor(0), tensor(9))

In [17]:
tensor[0] = 5
tensor

tensor([ 5., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [18]:
# changing the value of a specific index number
tensor[5] = 0
tensor

tensor([ 5., 10., 20., 30., 40.,  0., 60., 70., 80., 90.])

In [19]:
tensor.argmin()

tensor(5)

### Reshaping, stacking, squeezing and unsqueezing

1. Reshaping - reshaping a tensor to a specific shape
2. View - Return a view of input tensor
3. Stacking - stack tensors one over the other (vstack) or side by side (hstack)
4. Squeezing - remove `1` dimensions from the tensor
5. Unsqueezing - adds `1` dimensions to the tensor
6. Permute - return a view of input with dimensions permuted (swapped) in a certain way

In [21]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
x.reshape(1, 5, 2)

tensor([[[ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90]]])

In [28]:
# change the view of x
# z shares the memory with x and thus its just a different view of x so changing z changes x and same way round
z = x.view(1, 10)
z

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [29]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
x = x.reshape(1,5,2)

In [31]:
z

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [33]:
# stacking of tensors , dimension 0 is giving one tensor stacked over the other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[[[ 0, 10],
          [20, 30],
          [40, 50],
          [60, 70],
          [80, 90]]],


        [[[ 0, 10],
          [20, 30],
          [40, 50],
          [60, 70],
          [80, 90]]],


        [[[ 0, 10],
          [20, 30],
          [40, 50],
          [60, 70],
          [80, 90]]],


        [[[ 0, 10],
          [20, 30],
          [40, 50],
          [60, 70],
          [80, 90]]]])

In [34]:
x = x.reshape([1, 10])

In [35]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]],

        [[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]],

        [[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]],

        [[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]])

In [38]:
# Stacking Along Dimension 2: This means that a new dimension will be created at index 2, and the tensors will be stacked along this new dimension.
x_stacked = torch.stack([x, x, x, x], dim=2)
x_stacked

tensor([[[ 0,  0,  0,  0],
         [10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30],
         [40, 40, 40, 40],
         [50, 50, 50, 50],
         [60, 60, 60, 60],
         [70, 70, 70, 70],
         [80, 80, 80, 80],
         [90, 90, 90, 90]]])

In [52]:
x, x.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [54]:
# removes all single dimensions
x.squeeze(),x.squeeze().shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [55]:
# adds in single dimensions
x.unsqueeze, x.unsqueeze(dim  = 0).shape

(<function Tensor.unsqueeze>, torch.Size([1, 1, 10]))

In [60]:
# permute rearrange the dimensions in a view of original tensor and as view and tensor share the same memory its gonna have an overall impact
x_permuted = torch.permute(x, dims = (1, 0))
x_permuted , x_permuted.shape
# it changed the order of dimensions that was originally [1, 10] is now [10, 1]

(tensor([[ 0],
         [10],
         [20],
         [30],
         [40],
         [50],
         [60],
         [70],
         [80],
         [90]]),
 torch.Size([10, 1]))

In [62]:
x_permuted = x.permute(1, 0)
x_permuted.shape , x.shape

(torch.Size([10, 1]), torch.Size([1, 10]))

In [64]:
x[0,0] = 10
x

tensor([[10, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [65]:
x_permuted

tensor([[10],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

### Indexing (Selecting elements from tensor)

In [66]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
x[0, 1, 2]

tensor(6)

In [73]:
x[0][0]

tensor([1, 2, 3])

In [74]:
x[0][0][2]

tensor(3)

In [76]:
# we can use ":" to all of a target dimension
x[0,:,2]
# this returns the 2nd index values of all the three inner dimensions

tensor([3, 6, 9])

In [77]:
x[:,:,1]

tensor([[2, 5, 8]])

In [78]:
x[0,0,:]

tensor([1, 2, 3])

In [79]:
x[0, 2, 2]

tensor(9)