<a href="https://colab.research.google.com/github/arooba-zaman1211/Deep_Learning_using_Pytorch/blob/main/Lesson_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
int_32_tensor = torch.tensor([1.3,2.5,7.6],dtype=torch.int32)
int_32_tensor

tensor([1, 2, 7], dtype=torch.int32)

In [3]:
int_32_tensor.dtype

torch.int32

### Getting information from tensors (tensor attributes)

1. datatype - tensor.dtype
2. shape - tensor.shape
3. device - tensor.device

In [4]:
tensor = torch.rand(3,4)
tensor

tensor([[0.7903, 0.2718, 0.0529, 0.4434],
        [0.5360, 0.1493, 0.4111, 0.1578],
        [0.4760, 0.2174, 0.0595, 0.8664]])

In [5]:
tensor.dtype

torch.float32

In [6]:
tensor.shape

torch.Size([3, 4])

In [7]:
tensor.device

device(type='cpu')

In [8]:
tensor_2 = torch.randint(low=0, high=10,size = (2,4), dtype=torch.int16, device = 'cpu')
tensor_2

tensor([[0, 3, 5, 3],
        [6, 0, 2, 6]], dtype=torch.int16)

In [9]:
print(f"tensor_2 datatype: {tensor_2.dtype}")
print(f"tensor_2 device: {tensor_2.device}")
print(f"tensor_2 shape: {tensor_2.shape}")

tensor_2 datatype: torch.int16
tensor_2 device: cpu
tensor_2 shape: torch.Size([2, 4])


### Manipulating Tensor (tensor operations)

1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [10]:
tensor_2 + 10

tensor([[10, 13, 15, 13],
        [16, 10, 12, 16]], dtype=torch.int16)

In [11]:
tensor_2 - 10

tensor([[-10,  -7,  -5,  -7],
        [ -4, -10,  -8,  -4]], dtype=torch.int16)

In [12]:
tensor_2 / 10

tensor([[0.0000, 0.3000, 0.5000, 0.3000],
        [0.6000, 0.0000, 0.2000, 0.6000]])

In [13]:
tensor_2 * 10

tensor([[ 0, 30, 50, 30],
        [60,  0, 20, 60]], dtype=torch.int16)

In [14]:
# pytorch pre-defined functions
torch.mul(tensor_2, 10)

tensor([[ 0, 30, 50, 30],
        [60,  0, 20, 60]], dtype=torch.int16)

In [15]:
torch.add(tensor_2, 10)

tensor([[10, 13, 15, 13],
        [16, 10, 12, 16]], dtype=torch.int16)

### Matrix Multiplication

Two main ways of multiplication in neural networks and deep learning are:
1. Element wise multiplication
2. Matrix multiplication (dot product)

There are two conditions that needs to be satisfied for matrix multiplication:
1. Inner dimensions must match nxm mxn

*   torch.matmul(torch.rand(3,2), torch.rand(3,2)) this will throw an error
*   torch.matmul(torch.rand(3,2), torch.rand(2,4)) this will not throw an error

2. The resulting matrix has the shape of outer dimension

*  torch.matmul(torch.rand(3,2), torch.rand(2,4)) this will not throw an error
*  This resulting matrix has shape of 3x4



In [20]:
# matrix multiplication
tensor_4 = torch.tensor([2,3,4])
tensor_5 = torch.tensor([5,6,7])
mul_tensor = torch.matmul(tensor_4, tensor_5)
mul_tensor

tensor(56)

In [21]:
torch.matmul(torch.rand(3,2), torch.rand(2,4))

tensor([[0.9025, 1.4463, 0.9524, 0.7953],
        [0.4210, 0.5028, 0.4218, 0.3256],
        [0.8657, 1.4934, 0.9274, 0.7908]])

In [25]:
tensor_mul_1 = torch.tensor([[1,2],
              [3,4],
              [5,6]])
tensor_mul_2 = torch.tensor([[7,8],[9,10],[11,12]])
tensor_mul_1.shape, tensor_mul_2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#### There is a shape error and to solve it one way is to take transpose to get the matrices into shape

In [31]:
torch.matmul(tensor_mul_1, tensor_mul_2.T)
torch.matmul(tensor_mul_1, tensor_mul_2.T).shape

torch.Size([3, 3])