<a href="https://colab.research.google.com/github/arooba-zaman1211/Deep_Learning_Coding_Lessons/blob/main/Lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import torch
 print(torch.__version__)

2.3.1+cu121


## Introduction to Tensors

In [2]:
# scalar
# pytorch tensors are created using torch.tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# checking the rank(dimension) of a tensor as it is a scalar value that is 7 so its rank is 0
scalar.ndim

0

In [6]:
# to convert back to a scalar quantity rather than a tensor
scalar.item()

7

In [7]:
 # vector
 vector = torch.tensor([7,7])
 vector

tensor([7, 7])

In [8]:
# as it can be described using two components one for x and one for y so its rank is 1
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [15]:
# matrix dimension is 2
matrix = torch.tensor([[1,2],[3,4]])
matrix
# Axx,Axy
# Ayx,Ayy four components and two base vectors required so the order or rank is 2

tensor([[1, 2],
        [3, 4]])

In [11]:
matrix.ndim

2

In [13]:
matrix[1]

tensor([3, 4])

In [14]:
matrix.shape

torch.Size([2, 2])

In [17]:
 # Tensor
 TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
 TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape
#  The outer bracket shows the 1 in here that has everything rapped in it
# accessing it will print everything

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
# and then printing the next will give all the 2 base vector and 9 components
TENSOR[0,1,0]

tensor(4)

1. 0-dimensional tensor: A single number (scalar), e.g., torch.tensor(5)
2. 1-dimensional tensor: A vector, e.g., torch.tensor([1, 2, 3])
3. 2-dimensional tensor: A matrix, e.g., torch.tensor([[1, 2], [3, 4]])
4. N-dimensional tensor: An array with more than 2 dimensions.

When you define a tensor like torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]), it is a 3-dimensional tensor with a shape of (1, 3, 3). Here's why:

1. The outermost list [...] contains 1 element, which is itself a 2-dimensional matrix [[1, 2, 3], [4, 5, 6], [7, 8, 9]].
2. This 2-dimensional matrix is made up of 3 rows, each containing 3 elements.
To access each element, you need 3 indices: [0, x, y].
3. The first index selects the "slice" (there is only one slice here, so it's always 0), the second index selects the row, and the third index selects the column within that row.

In simpler terms, the number of dimensions tells you how many levels of nested lists you have:

1. [1, 2, 3] is 1-dimensional.
2. [[1, 2], [3, 4]] is 2-dimensional.
3. [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] is 3-dimensional.

In [25]:
!apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.


In [26]:
!git clone https://github.com/arooba-zaman1211/Deep_Learning_Coding_Lessons.git

Cloning into 'Deep_Learning_Coding_Lessons'...
