<a href="https://colab.research.google.com/github/arooba-zaman1211/Deep_Learning_using_Pytorch/blob/main/Lesson_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
T = torch.tensor([[[[1,2,3],[4,5,6]]]])
T

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [4]:
T.ndim

4

In [5]:
T.shape

torch.Size([1, 1, 2, 3])

1. Batch Size (1): This dimension represents the number of samples in a batch. In many deep learning tasks, you process multiple samples at once for efficiency. In this case, the batch size is 1, meaning there's only one sample in the batch.

2. Channels (1): This dimension typically represents the number of channels or features in the data. For example, in image data, this could be the number of color channels (e.g., 3 for RGB images). Here, there is only one channel, which could represent a grayscale image or a single feature map.

3. Height (2): This dimension represents the number of rows in the data. In the context of images, this is the height of the image or feature map. Here, the height is 2, so the data has 2 rows.

4. Width (3): This dimension represents the number of columns in the data. In images, this is the width of the image or feature map. Here, the width is 3, so the data has 3 columns.

### Random tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers-> look at data-> update random numbers-> look at data-> update random numbers`

In [6]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6243, 0.8417, 0.4228, 0.5172],
        [0.6482, 0.0011, 0.0465, 0.5274],
        [0.8391, 0.2152, 0.3442, 0.2008]])

In [7]:
random_tensor.ndim

2

In [8]:
# to create more dimensions we have to give another argument to this function
random_tensor2 = torch.rand(1,2,4)
random_tensor2

tensor([[[0.8427, 0.6124, 0.4919, 0.7084],
         [0.7415, 0.9666, 0.8423, 0.2825]]])

In [9]:
 random_tensor2.ndim

3

In [12]:
# Create a random tensor with similar shape to an image tensor

random_image = torch.rand(size=(224,224,3)) # height, width and color channels
random_image.shape, random_image.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
# If you need a tensor with 4 dimensions, you can add another dimension
random_tensor3 = torch.rand(1,5,10,10)
random_tensor3

tensor([[[[0.6702, 0.4197, 0.1262, 0.1289, 0.5131, 0.0370, 0.1586, 0.4491,
           0.6566, 0.6763],
          [0.1554, 0.0451, 0.9775, 0.8062, 0.8467, 0.8139, 0.7772, 0.3522,
           0.3202, 0.2226],
          [0.7387, 0.9599, 0.0968, 0.8085, 0.9092, 0.0353, 0.4325, 0.9209,
           0.8910, 0.2603],
          [0.4005, 0.1649, 0.6326, 0.1357, 0.5473, 0.4121, 0.2831, 0.8120,
           0.8645, 0.3230],
          [0.0239, 0.4103, 0.9725, 0.5293, 0.5359, 0.3837, 0.1515, 0.3183,
           0.4687, 0.3941],
          [0.7708, 0.3531, 0.8298, 0.4947, 0.3174, 0.8015, 0.2484, 0.6846,
           0.3581, 0.3615],
          [0.3520, 0.5137, 0.5082, 0.4577, 0.0652, 0.6748, 0.6315, 0.8517,
           0.1144, 0.7782],
          [0.5780, 0.7592, 0.2405, 0.3889, 0.1950, 0.0281, 0.4690, 0.2516,
           0.3461, 0.3040],
          [0.3134, 0.1277, 0.4990, 0.4674, 0.2078, 0.7754, 0.7841, 0.4972,
           0.1862, 0.8521],
          [0.1307, 0.9038, 0.6064, 0.0383, 0.8116, 0.5722, 0.3565, 0.8085

In [16]:
random_tensor3.ndim

4

### Zeros and ones

In [18]:
 zeros = torch.zeros(3,4)
 zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones * random_tensor

tensor([[0.6243, 0.8417, 0.4228, 0.5172],
        [0.6482, 0.0011, 0.0465, 0.5274],
        [0.8391, 0.2152, 0.3442, 0.2008]])

In [25]:
zeros * random_tensor[0,1]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * random_tensor[0,:]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
random_tensor = torch.rand(5,3,4)
random_tensor

tensor([[[0.2724, 0.3893, 0.9723, 0.3899],
         [0.4726, 0.9836, 0.9843, 0.2562],
         [0.4824, 0.1676, 0.2181, 0.5755]],

        [[0.8266, 0.2633, 0.3334, 0.8933],
         [0.0972, 0.7582, 0.5374, 0.7197],
         [0.5133, 0.5362, 0.9120, 0.4415]],

        [[0.5891, 0.1071, 0.0269, 0.9408],
         [0.8568, 0.6006, 0.5072, 0.8562],
         [0.9081, 0.6231, 0.8027, 0.5013]],

        [[0.3984, 0.9605, 0.5555, 0.3318],
         [0.9398, 0.7031, 0.9139, 0.2843],
         [0.2379, 0.8563, 0.7526, 0.3812]],

        [[0.4778, 0.0247, 0.0174, 0.8658],
         [0.1263, 0.3923, 0.3506, 0.0541],
         [0.8394, 0.3276, 0.6205, 0.7078]]])

In [33]:
zeros * random_tensor[:,:,:]

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])